# Generated by Django 6.0.4 on 2026-04-27 18:46

import apps.salons.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=20)),
                ("timezone", models.CharField(default="Europe/Moscow", max_length=50)),
                ("yclients_company_id", models.IntegerField(blank=True, null=True)),
                (
                    "yclients_user_token",
                    apps.salons.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "yclients_partner_token",
                    apps.salons.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "telegram_bot_token",
                    apps.salons.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "telegram_bot_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "max_bot_token",
                    apps.salons.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "wazzup_api_key",
                    apps.salons.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "wazzup_channel_id_whatsapp",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "wazzup_channel_id_instagram",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("system_prompt_override", models.TextField(blank=True)),
                (
                    "ai_model",
                    models.CharField(default="claude-sonnet-4-6", max_length=50),
                ),
                (
                    "admin_telegram_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("working_hours_json", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Салон",
                "verbose_name_plural": "Салоны",
            },
        ),
    ]
