# Generated by Django 6.0.4 on 2026-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salons", "0002_add_salon_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="ai_model",
            field=models.CharField(default="llama-3.3-70b-versatile", max_length=50),
        ),
        migrations.AlterField(
            model_name="salon",
            name="working_hours_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
