# Generated by Django 5.2.13 on 2026-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0003_alter_salon_ai_model_alter_salon_working_hours_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="ai_model",
            field=models.CharField(default="gpt-4o-mini", max_length=50),
        ),
    ]
