# Generated by Django 6.0.4 on 2026-04-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("salons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("faq", "FAQ"),
                            ("policy", "Policy"),
                            ("price", "Price info"),
                            ("service_description", "Service description"),
                            ("general", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("qdrant_point_ids", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_docs",
                        to="salons.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ базы знаний",
                "verbose_name_plural": "База знаний",
            },
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yclients_id", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("specialization", models.CharField(blank=True, max_length=300)),
                ("bio", models.TextField(blank=True)),
                ("service_ids", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masters",
                        to="salons.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мастер",
                "verbose_name_plural": "Мастера",
                "unique_together": {("salon", "yclients_id")},
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yclients_id", models.IntegerField()),
                ("title", models.CharField(max_length=300)),
                ("category", models.CharField(blank=True, max_length=200)),
                ("duration_minutes", models.IntegerField()),
                ("price_min", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="salons.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "unique_together": {("salon", "yclients_id")},
            },
        ),
    ]
