# Generated by Django 6.0.4 on 2026-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='yclients_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='yclients_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
