# Generated by Django 6.0.4 on 2026-04-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialogs", "0001_initial"),
        ("knowledge_base", "0001_initial"),
        ("salons", "0003_alter_salon_ai_model_alter_salon_working_hours_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="master",
            name="service_ids",
        ),
        migrations.AddField(
            model_name="master",
            name="experience_years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="master",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="masters", to="knowledge_base.service"
            ),
        ),
        migrations.AlterField(
            model_name="master",
            name="yclients_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="yclients_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_phone", models.CharField(max_length=20)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                            ("no_show", "Не пришёл"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dialogs.conversation",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="knowledge_base.master",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="salons.salon",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="knowledge_base.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "indexes": [
                    models.Index(
                        fields=["salon", "starts_at"],
                        name="knowledge_b_salon_i_dcb601_idx",
                    ),
                    models.Index(
                        fields=["master", "starts_at"],
                        name="knowledge_b_master__f48bf9_idx",
                    ),
                ],
            },
        ),
    ]
