# Generated by Django 6.0.4 on 2026-04-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_alter_master_yclients_id_alter_service_yclients_id'),
        ('knowledge_base', '0002_local_booking_support'),
    ]

    operations = [
    ]
