# Generated by Django 5.2.13 on 2026-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0003_merge_20260430_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
