# Generated by Django 5.2.13 on 2026-05-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogs", "0001_initial"),
        ("salons", "0004_openai_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dialogs.conversation",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="salons.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Использование AI",
                "verbose_name_plural": "Использование AI",
                "indexes": [
                    models.Index(
                        fields=["salon", "created_at"],
                        name="dialogs_aiu_salon_i_48c1d5_idx",
                    )
                ],
            },
        ),
    ]
