# Generated by Django 6.0.4 on 2026-04-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("salons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalonClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id_yclients",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("preferred_channel", models.CharField(blank=True, max_length=20)),
                ("last_visit_date", models.DateTimeField(blank=True, null=True)),
                ("total_visits", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="salons.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "indexes": [
                    models.Index(
                        fields=["salon", "external_id_yclients"],
                        name="clients_sal_salon_i_102919_idx",
                    )
                ],
                "unique_together": {("salon", "phone")},
            },
        ),
    ]
